### ISSUE TITLE
Current setup.py references vegalite not in altair

### ISSUE THREAD

**Issue by polyatail** [vega/ipyvega#101]
The most recent change to `setup.py` switched to `altair.vegalite.v3` which currently does not exist in altair, causing `altair.renderers.enable('notebook')` to fail.

```
ENTRY_POINTS        = {'altair.vegalite.v3.renderer': ['notebook=vega.vegalite:entry_point_renderer'],
                       'altair.vega.v4.renderer': ['notebook=vega.vega:entry_point_renderer']
```

**Comment by domoritz** [comment]
Please use v2 released on pypi as a pre-release: https://pypi.org/project/vega/#history.
