### ISSUE TITLE
widget breaks v2.3.0 

### ISSUE THREAD

**Issue by chmp** [vega/ipyvega#105]
@domoritz bad news ... I just tried to use the most recent ipyvega version (2.3.0) and somehow the widget code seems to break the notebook extension. I have not yet figured out what is different to the env I tested everything on, but I wanted to give you a heads up, in case you would like to revert the merge, while I investigate. :/

**Comment by jakevdp** [comment]
Also reported here: https://github.com/altair-viz/altair/issues/1550#issuecomment-502136304

The issue is that ipywidgets is specified as an extra requirement, which is true on the Python side. But the associated javascript dependencies are a hard requirement on the javascript side, as specified by the ``require`` statement. So if you try to use vega 2.3 on a jupyter instance that does not have the ipywidgets extension installed, it will lead to a javascript error.

**Comment by domoritz** [comment]
Okay, I am investigating this right now. Thanks for flagging it.

**Comment by domoritz** [comment]
On my machine conda installed the ipywidgets extension so I didn't notice the problem. The `resolveWeak` should make things work even if you don't have the widgets js code installed.

**Comment by domoritz** [comment]
Hmm, I don't see any JS errors other than the 404, but that shouldn't crash the whole renderer. 

<img width="510" alt="Screen Shot 2019-06-14 at 10 40 26" src="https://user-images.githubusercontent.com/589034/59527595-e4688280-8e90-11e9-9af2-d82e53eb19bf.png">

**Comment by domoritz** [comment]
I added a try catch in 2.3.1. Can you try it?

**Comment by chmp** [comment]
Still doesn't work for me.

**Comment by domoritz** [comment]
Weird, it works for me locally even when I uninstall the widgets extension. I also don't see an error so I'm not sure where things are breaking.

**Comment by chmp** [comment]
Do you install with `-e`? I have the feeling there is a diff between that and normal installs.

**Comment by domoritz** [comment]
I installed with `python setup.py develop` as described in https://github.com/vega/ipyvega#developers

**Comment by chmp** [comment]
Should be equiv to `-e`. Most likely it breaks if you install it with `pip install .`.

**Comment by domoritz** [comment]
Okay, I don't see the error so I am going to revert the widget PR for now. Can you send a new PR that works @chmp?

**Comment by chmp** [comment]
Yes. I will continue to investigate.

**Comment by domoritz** [comment]
Thank you! I love the widget functionality and definitely want to have it in a future release.

**Comment by domoritz** [comment]
Fixed in vega-2.3.2

**Comment by jakevdp** [comment]
Thanks Dom
