### ISSUE TITLE
ipyvega & Voila

### ISSUE THREAD

**Issue by DentonGentry** [vega/ipyvega#109]
This is mostly an FYI for people searching for [voila](https://blog.jupyter.org/and-voil%C3%A0-f6a2c08a4a93) support with ipyvega: from https://github.com/QuantStack/voila/issues/354, one must pass the "--enable_nbextensions=True" when starting voila for ipyvega to work, because ipyvega is not released in npm.

**Comment by domoritz** [comment]
Thanks for posting this. I'm going to close this issue since there is no immediate Todo but feel free to comment here. 

Is there something we could do to help you?
