### ISSUE TITLE
Possibility to set locale (formatLocale)?

### ISSUE THREAD

**Issue by sahrmann** [vega/ipyvega#135]
It would be great to be able to set a different locale for dates and number formatting (Vega formatLocale function). Is there any chance to use the jupyter or browser locale?

I tried to add the respective calls to the render() method in the index.ts file, but a call to formatLocale does not change the appearance. Any help would be greatly appreciated!

**Comment by domoritz** [comment]
Duplicate of https://github.com/vega/vega-embed/issues
