### ISSUE TITLE
is ipyvega included in jupyter notebook by default?

### ISSUE THREAD

**Issue by jiapei100** [vega/ipyvega#162]
```console
➜  vega git:(master) jupyter notebook --version
6.0.3
```

**jupyter nbextension install --sys-prefix --py vega  # not needed in notebook >= 5.3**

**Comment by jakevdp** [comment]
No, it must be installed from pip. In notebook version 5.3 or newer, pip installing the package is sufficient to install the nbextension. Previous to that, the nbextension had to be installed manually.
