### ISSUE TITLE
Unrecognized transform type: "kde2d"

### ISSUE THREAD

**Issue by Flave** [vega/ipyvega#163]
When simply pasting the vega specification from the [contour plot example](https://vega.github.io/vega/examples/contour-plot/) into a notebook like so `Vega(<spec>)` I get the following error:

```
Javascript Error: Unrecognized transform type: "kde2d"

This usually means there's a typo in your chart specification. See the JavaScript console for the full traceback.
```

Is it possible that ipyvega `vega-3.0.2` uses an older version than 5.8 of the underlying vega implementation?

**Comment by domoritz** [comment]
Hmm, it's using 5.9.1 https://github.com/vega/ipyvega/blob/master/yarn.lock#L3425. I'm not sure what's going wrong here.

**Comment by domoritz** [comment]
Please use the package version 3.1
