### ISSUE TITLE
Conda Installation of vega 3.0.2 Requires Installation of pre-1.0 Pandas

### ISSUE THREAD

**Issue by apahl** [vega/ipyvega#170]
Hi,

when I try to install Pandas and the latest vega (3.0.2) via conda for Python 3.8, a pre-1.0 version of Pandas gets installed (abbr. conda output):

```
$ conda create -c conda-forge -n chem python=3.8 pandas altair vega
  altair             conda-forge/noarch::altair-4.0.1-py_0
  pandas             conda-forge/linux-64::pandas-0.25.3-py38hb3f55d8_0
  python             conda-forge/linux-64::python-3.8.1-h357f687_2
  vega               conda-forge/linux-64::vega-3.0.2-py38_0
```

Whereas when I explicitly install an earlier vega version, the latest Pandas gets installed (abbr. conda output):
```
$ conda create -c conda-forge -n chem python=3.8 pandas altair vega=2.6

  altair             conda-forge/noarch::altair-4.0.1-py_0
  pandas             conda-forge/linux-64::pandas-1.0.1-py38hb3f55d8_0
  python             conda-forge/linux-64::python-3.8.1-h357f687_2
  vega               conda-forge/linux-64::vega-2.6.0-py38_0
```

Would it be possible to make the newest version of vega compatible with the latest Pandas?

Many thanks for your help.

Kind regards,  
Axel

**Comment by domoritz** [comment]
Thanks for raising the issue. I'll make an update.

**Comment by apahl** [comment]
Thanks a lot. Has this been mirrored to conda-forge already? Because I still get the above mentioned behaviour.  
KR Axel

**Comment by domoritz** [comment]
Yes

**Comment by apahl** [comment]
Sorry to keep bothering you with this, but vega >=3.0 still pulls the old Pandas versions via conda-forge.

KR Axel
