### ISSUE TITLE
Altair's "notebook" renderer is no longer working

### ISSUE THREAD

**Issue by b11z** [vega/ipyvega#179]
Hi there, I noticed that the jupyter notebook integration of altair (following altair's [instructions for displaying in the jupyter notebook](https://altair-viz.github.io/user_guide/display_frontends.html#displaying-in-the-jupyter-notebook) doesn't work in the latest release of ipyvega. It instead gives:
> To use the 'notebook' renderer, you must install the vega package and the associated Jupyter extension. See https://altair-viz.github.io/getting_started/installation.html for more information.

I believe this was caused by the switch over to poetry -- I see that the old setup.py had:
```
ENTRY_POINTS        = {'altair.vegalite.v4.renderer': ['notebook=vega.vegalite:entry_point_renderer'],
                       'altair.vega.v5.renderer': ['notebook=vega.vega:entry_point_renderer']
                      }
```
and I believe that removing that has broken the notebook/altair integration.

I was able to workaround with:
```
import vega.vegalite
import vega.vega

alt.vegalite.v4.renderers.register('notebook', vega.vegalite.entry_point_renderer)
alt.v4.renderers.register('notebook', vega.vega.entry_point_renderer)
```

Thanks & hope this helps!

**Comment by domoritz** [comment]
Oh, thank you for posting this issue. Do you have a suggestion for how to fix this?

**Comment by jakevdp** [comment]
This looks relevant: https://github.com/python-poetry/poetry/issues/658

**Comment by jakevdp** [comment]
We'd have to test it, but I think the config needs something like this:
```
[tool.poetry.plugins."altair.vegalite.v4.renderer"]
notebook = "vega.vegalite:entry_point_renderer"

[tool.poetry.plugins."altair.vega.v5.renderer"]
notebook = "vega.vega:entry_point_renderer"
```

**Comment by domoritz** [comment]
I didn't realize that ipyvega needs to be aware of Altair. I'll add a notebook with Altair so I'm not accidentally breaking it again.

**Comment by domoritz** [comment]
Hmm, Altair actually works for me without any changes. 

<img width="1154" alt="Screen Shot 2020-03-20 at 16 28 55" src="https://user-images.githubusercontent.com/589034/77213399-e7e80480-6ac7-11ea-84fc-117ad11f51b4.png">

Do you have issues running https://github.com/vega/ipyvega/blob/master/notebooks/Altair.ipynb after running `poetry shell` and `jupyter notebook`?

**Comment by jakevdp** [comment]
This is expected – see https://altair-viz.github.io/user_guide/display_frontends.html?highlight=notebook%20renderer#displaying-in-the-jupyter-notebook

You'll see the issue if you run ``alt.renderers.enable('notebook')`` to enable offline rendering via this extension, the renderer is not available.

**Comment by domoritz** [comment]
Ahh. After I add the lines you posted, the offline mode works. 

<img width="1122" alt="Screen Shot 2020-03-20 at 17 06 56" src="https://user-images.githubusercontent.com/589034/77214609-406dd080-6acd-11ea-82af-cb386171d1ca.png">

I'll make a release.

**Comment by domoritz** [comment]
Fixed and released in 3.2.0

**Comment by jakevdp** [comment]
Thanks!

**Comment by domoritz** [comment]
Thank you.
