### ISSUE TITLE
Add voyager and polestar back

### ISSUE THREAD

**Issue by domoritz** [vega/ipyvega#25]
Support for these tools has been removed in https://github.com/vega/ipython-vega/pull/23. It would be great to add it back using the new nbextensions.

**Comment by domoritz** [comment]
Will be done somewhere else.

**Comment by AhmedThahir** [comment]
> Will be done somewhere else.

Can you share where this is?

**Comment by domoritz** [comment]
We don't have a package but code is at https://github.com/vega/voyager and it should be fairly straight forward to make a package with anywidget these days.
