### ISSUE TITLE
Make plots show on nbviewer

### ISSUE THREAD

**Issue by jakevdp** [vega/ipyvega#29]
Currently plots don't render on nbviewer. I'm not sure how to address this, but I think @ellisonbg has some ideas.

**Comment by domoritz** [comment]
Looks like this is a known issue with nbviewer https://github.com/jupyter/nbviewer/issues/263

**Comment by domoritz** [comment]
As a workaround, we could implement the export functionality in https://github.com/vega/ipyvega/issues/3 .

**Comment by ellisonbg** [comment]
Done in #32
