### ISSUE TITLE
Export VL chart

### ISSUE THREAD

**Issue by domoritz** [vega/ipyvega#3]
When you are done with your exploration, you probably want to have a visualization in a separate cell. We should make this process simple.

**Comment by domoritz** [comment]
use `set_next_input`

**Comment by domoritz** [comment]
@kanitw Can you think of a way to call polestar and get the current spec? Basically, is there a way to make a function available to the outside world?

**Comment by kanitw** [comment]
I'm feeling like if we want to provide nice interface for development.
Wrapping our app using Polymer will provide nice interface.
I was searching a bit if we can wrap an angular app inside polymer but
haven't found satisfying one though.

Kanit "Ham" Wongsuphasawat
Graduate Student
Computer Science & Engineering
University of Washington
http://kanitw.yellowpigz.com
