### ISSUE TITLE
Serve data from server extension

### ISSUE THREAD

**Issue by domoritz** [vega/ipyvega#30]
Instead of embedding the data as serialized json in the notebook, the data should be served from the kernel (through a server extension) if that's possible.

@ellisonbg could you tell us whether this is possible and how we roughly would go about this?

**Comment by ellisonbg** [comment]
A server extension is not even necessary as you can put files on the filesystem and just refer to them by path.

But I definitely would not go this route as it will make it even more difficult to get it working on nbviewer or github in the future. An alternative to what you are doing right now (throwing raw json text in the notebook's HTML) would be to send back JSON output and access the cells output area. Then the extension could just grab that JSON data. I will try to work up a simple example showing how this could be done.

**Comment by domoritz** [comment]
We can now load files by path.
