### ISSUE TITLE
Create GitHub Milestone for a release

### ISSUE THREAD

**Issue by ellisonbg** [vega/ipyvega#34]
Having a GH Milestone for the release will help us to target issues to the release.

What version number do we want the release to be?

**Comment by jakevdp** [comment]
Let's do 0.3 for now, battle-test it a bit, and then 1.0 once we work-out any problems.

**Comment by ellisonbg** [comment]
Sounds good.

**Comment by domoritz** [comment]
Since this repo now contains vega and vega 3, this will be tricky. We do tag releases of the vega package.
