### ISSUE TITLE
Write `py.test` based tests for things that are easy to test

### ISSUE THREAD

**Issue by ellisonbg** [vega/ipyvega#36]
- [x] Things in utils.py, especially `prepare_spec` and `sanitize_dataframe`.
- [x] At least import things from the `base.py`, `vega.py` and `vegalite.py`.

**Comment by domoritz** [comment]
I added travis so now we only need to write the tests ;-)

**Comment by jakevdp** [comment]
Awesome! I think there was one test in my recent sanitize PR. I'll look into writing some others after the kid goes to bed tonight (my most productive hours...)

**Comment by domoritz** [comment]
> Awesome! I think there was one test in my recent sanitize PR.

I took that as an incentive to add travis. It's already cunning your test https://travis-ci.org/vega/ipyvega/jobs/135452366

**Comment by jakevdp** [comment]
Awesome!

**Comment by jakevdp** [comment]
Started on this at #46

**Comment by jakevdp** [comment]
OK – #46 should now hit all items in this issue.
