### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by ellisonbg** [vega/ipyvega#37]
I haven't looked, but after #32  is merged, we should probably update the README:
- [x] Provide links to the demo notebooks on GitHub and nbviewer.
- [x] Start to promote that it works on GitHub and nbviewer.
- [x] Audit the installation and dev instructions.
- [ ] Update screenshots for vega+vegalite.

**Comment by domoritz** [comment]
Link to https://github.com/conda-forge/vega-feedstock?

**Comment by domoritz** [comment]
I updated the readme except for the screenshot. I'm not sure it's too important to show both Vega and Vega-Lite in the screenshot.
