### ISSUE TITLE
VegaWidget doesn't appear to work with ipywidgets.embed

### ISSUE THREAD

**Issue by cpsievert** [vega/ipyvega#376]
Something must be wrong with the JS behind `VegaWidget()` since this python code runs without error

```python
import altair as alt
from vega.widget import VegaWidget
from vega_datasets import data
from ipywidgets.embed import embed_minimal_html
p = (
    alt.Chart(data.cars())
    .mark_point()
    .encode(
        x="Horsepower",
        y="Miles_per_Gallon",
        color="Origin",
    )
)
w = VegaWidget(p.to_dict())
embed_minimal_html("index.html", views=[w])
```

However, when I try to view the HTML, I see the following JS errors

```shell
python3 -m http.server
```

<img width="1013" alt="Screen Shot 2021-11-29 at 10 25 53 AM" src="https://user-images.githubusercontent.com/1365941/143905449-1a41b167-6e62-408b-a0ef-62b35986e744.png">

**Comment by domoritz** [comment]
i'm not sure what `ipywidgets.embed` is. Is this bug something you can help with?

**Comment by cpsievert** [comment]
> i'm not sure what ipywidgets.embed is.

It's ipywidget's official API for saving widgets in a static HTML file https://ipywidgets.readthedocs.io/en/stable/embedding.html#python-interface

(BTW, I know `altair` plots can be rendered to HTML without ipywidgets, but in my case, it'd be convenient to render ipywidgets)

> Is this bug something you can help with?

I can try. Just having a quick look over the source, _I think_ the main issue derives from here:

https://github.com/vega/ipyvega/blob/ea377379de5c48514a39d833996f03327ee6fe43/vega/widget.py#L66

IIUC, this is basically assuming that `require("nbextensions/jupyter-vega/widget")` is available, which isn't true for a static HTML context. I think changing that line to `jupyter-vega` and publishing the npm package will resolve the issue?

**Comment by domoritz** [comment]
Could you prepare a pull request where `jupyter-vega` is in a separate directory so I can make releases to npm easily. Do we also need a yarn workspaces setup then or how will the import in development work?

**Comment by cpsievert** [comment]
Sure, I'll send you a PR and try to follow the cookiecutter template as much as possible https://github.com/jupyter-widgets/widget-cookiecutter/tree/master/%7B%7Bcookiecutter.github_project_name%7D%7D/js
