### ISSUE TITLE
use case: vincent replacement, using python

### ISSUE THREAD

**Issue by jowens** [vega/ipyvega#4]
Per Dominik's request, I'm attaching my use case, and hope to work with the authors to make this use case work.

My workflow is simulation -> JSON -> pandas -> ? -> vega. Currently the ? is vincent, but vincent is not Vega-2.0-compliant and the author, who did a great job on it, isn't currently maintaining it. My simulation generates a lot of data; pandas is exactly the right tool (in python) for slicing and dicing that data; my hope is this package will fill in the ? where vincent is currently kind-of doing the job.

I am less interested in the ipython case and more interested in just using plain python as a batch script, but I think I will try out ipython since that is a design goal for y'all. I will also have suggestions on how to write good docs/examples that make it easy for others to use your tool. (This is a place where vincent could improve. What I will suggest is that for a given plot type, you explicitly say what it expects as an argument in terms of a pandas DataFrame, for instance, "GroupedBar: expects a pandas DataFrame where the rows are a set of measurements that are grouped together (in the GroupedBar 'group'), and each column is one individual measurement").

It is also my hope that I can generate both web plots (via D3, in the web browser) as well as print plots (SVG, PDF, etc.).

Thanks for writing this!

**Comment by domoritz** [comment]
Sorry for the late reply. For your use case, you can simply use [vega-lite](https://github.com/uwdata/vega-lite) with node. Vega-lite is written in javascript and takes a simple visualization specification and translates it to vega. 

A bar chart for example can be written as:
```json
{
  "marktype": "bar",
  "encoding": {
    "y": {"type": "Q","name": "y"},
    "x": {"type": "O","name": "x"}
  }
}
```

If you want to also add all the data to the spec itself, just convert your [pandas dataframe to json](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_json.html) and add it as the data attribute like this:

```json
{
  "data": {
    "values": [
      {"x":"A", "y":28}, {"x":"B", "y":55}, {"x":"C", "y":43},
      {"x":"D", "y":91}, {"x":"E", "y":81}, {"x":"F", "y":53},
      {"x":"G", "y":19}, {"x":"H", "y":87}, {"x":"I", "y":52}
    ]
  },
  "marktype": "bar",
  "encoding": {
    "y": {"type": "Q","name": "y"},
    "x": {"type": "O","name": "x"}
  }
}
```

I think you will only need maybe 10 lines of code or so to make the code work for your use case. Write a python script that generates the vega lite spec as JSON and then a [little node script that takes a vl json spec and returns a vega spec](https://github.com/uwdata/vega-lite/issues/562). I will implement the second part for you (https://github.com/uwdata/vega-lite/issues/562).

**Comment by jowens** [comment]
I'll give this a try. Stay tuned for feedback (and perhaps a question or two).

**Comment by domoritz** [comment]
Great, I'll finish the cli tool and cc you.

**Comment by jowens** [comment]
Just FYI, none of the 5 'orient' options in pandas's to_json call correspond to what vl expects. In particular, the "x" and "y" designations don't have an equivalent in terms of to_json. (I can munge it into the right format, of course.) I don't really know if there are other ways that vl can accept a "data" argument, hence https://github.com/uwdata/vega-lite/issues/566 .

**Comment by domoritz** [comment]
I wrote this: https://github.com/uwdata/ipython-vega-lite/blob/master/vega/polestar.py#L62

```python
    def __data(self):
        res = []
        for row in self.data.tolist():
            res.append({k: v for k, v in zip(self.columns, row)})
        return res
```

**Comment by domoritz** [comment]
I believe we are much closer to this now. What's missing seems to be covered by other issues.
