### ISSUE TITLE
Support Jupyterlab

### ISSUE THREAD

**Issue by mangecoeur** [vega/ipyvega#432]
I'm getting an 'Error displaying widget: model not found' in jupyterlab - although it works using the voila extension within jupyterlab but i assume the widgets are loaded differently. Is jupyterlab supported? Console shows  `Module jupyter-vega, semver range 3.6.0 is not registered as a widget module`

**Comment by domoritz** [comment]
Jupyterlab has Vega built in via mime types so you don't need this extension to render charts. I have not tested in for widgets in jupyterlab.

**Comment by mangecoeur** [comment]
Thanks, my interest in ipyvega is to embed plots in ipywidget layouts that i turn into dashboards with voila. It’s technically possible to use ipython output widgets but from experience this is much more clunky and fragile than using a true widget with state syncing. Do you know where i should start looking to debug this? I know other widget libraries had to update to support jupyter lab but i don’t know what exactly has to change.

**Comment by domoritz** [comment]
Can you try again with the latest master? I think it works in lab now since we even test against it in the UI tests.
