### ISSUE TITLE
Move dependencies from ui-tests to main package.json

### ISSUE THREAD

**Issue by domoritz** [vega/ipyvega#462]
It's not very clean to have a second package.json that doesn't even have a lock file as dependencies might break at any point. Instead, we should move the dependencies to the top level and only reference them in the ui tests directory. We could even move the scripts to the top level.

**Comment by xtianpoli** [comment]
There is no dependency (or dev dependency) between ipyvega and galata. Galata works in the same way whatever the notebook tested, whether it contains widgets or not: runs it cell by cell, captures a screenshot of the cell outputs then compare with references.

I guess this is why all the Jupyter project repositories using Galata prefer a separate test package management with a dedicated package.json in the ui-tests directory:

- https://github.com/jupyter-widgets/ipywidgets/tree/main/ui-tests

- https://github.com/jupyter-widgets/ipyleaflet/tree/master/ui-tests

On the other hand, a lockfile is necessary, indeed.

**Comment by domoritz** [comment]
The issue is that dependably doesn't update the nested packages I think. We could add a second entry for the tests to resolve this issue, I guess.

**Comment by xtianpoli** [comment]
This should work: https://github.com/dependabot/dependabot-core/issues/2824#issuecomment-741693711

**Comment by domoritz** [comment]
Great. Let's do that here then.
