### ISSUE TITLE
pandas-2.0 support ?

### ISSUE THREAD

**Issue by stonebig** [vega/ipyvega#477]
is there an incompatibility that don't allow support for Pandas 2.0.1 ?

**Comment by domoritz** [comment]
Not that I know of.

**Comment by stonebig** [comment]
so would it be possible toremove the constraint pandas <2 from the vega-4.0.0 wheel ?

![image](https://user-images.githubusercontent.com/4312421/235184582-bbe15c7e-824d-44ca-9bd1-d17b52e7ec1d.png)

<details>
Metadata-Version: 2.1
Name: vega
Version: 4.0.0
Summary: A Jupyter widget for Vega 5 and Vega-Lite 4
Home-page: https://github.com/vega/ipyvega
License: BSD 3-clause
Author: Dominik Moritz
Author-email: domoritz@gmail.com
Requires-Python: >=3.8.0
Classifier: Development Status :: 5 - Production/Stable
Classifier: Environment :: Console
Classifier: Intended Audience :: Science/Research
Classifier: License :: OSI Approved :: BSD License
Classifier: License :: Other/Proprietary License
Classifier: Natural Language :: English
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.8
Classifier: Programming Language :: Python :: 3.9
Classifier: Programming Language :: Python :: 3.10
Classifier: Programming Language :: Python :: 3.11
Classifier: Programming Language :: Python :: 3.10
Classifier: Programming Language :: Python :: 3.11
Classifier: Programming Language :: Python :: 3.8
Classifier: Programming Language :: Python :: 3.9
Provides-Extra: jupyterlab
Provides-Extra: widget
Requires-Dist: ipytablewidgets (>=0.3.0,<0.4.0)
Requires-Dist: jupyter (>=1.0.0,<2.0.0)
Requires-Dist: pandas (>=1.5.0,<2.0.0)
Project-URL: Repository, https://github.com/vega/ipyvega
Description-Content-Type: text/x-rst

IPython Vega
============

IPython/Jupyter notebook module for `Vega <https://github.com/vega/vega/>`_
and `Vega-Lite <https://github.com/vega/vega-lite/>`_.
Notebooks with embedded visualizations can be viewed on GitHub and nbviewer.

For more information, see https://github.com/vega/ipyvega.

Installation Notes
------------------
When installing from PyPI, extra steps may be required to enable the Jupyter
notebook extension. For more information, see the
`github page <https://github.com/vega/ipyvega>`_.


</details>

**Comment by domoritz** [comment]
I think so. Can you send a pull request?

**Comment by WimYedema** [comment]
It's been over a year... Can this be released? (or pre-released)

**Comment by domoritz** [comment]
I'll look into it. Somehow tests are not passing anymore with small updates so this needs to be cleaned up first.

**Comment by domoritz** [comment]
I'm publishing 4.1

**Comment by WimYedema** [comment]
Thanks
