### ISSUE TITLE
Need new release which supports vega 1.0.12

### ISSUE THREAD

**Issue by jakevdp** [vega/ipyvega#49]
So that it will work with the upcoming altair release.

Once it's on PyPI, I can update the conda recipe.

**Comment by domoritz** [comment]
I just released a new version.

**Comment by jakevdp** [comment]
Thanks!

**Comment by jakevdp** [comment]
Looks like the release [on PyPI](https://pypi.python.org/pypi/vega) is ``0.4.dev0``. PyPI doesn't know about package.json, so it reads the version from ``vega/__init__.py`` – can you update that and re-release?

There's probably a way we could make that more automatic, but that's something to think about later.

**Comment by domoritz** [comment]
That was on purpose. I don't understand what the .dev0 ending means. What
should the release number be?

**Comment by jakevdp** [comment]
In my experience, .dev indicates a release is in development so that, for example, if you install from master you can immediately see that it's a development version rather than a release. Upon release, that's changed to whatever version the release is, e.g. ``0.4``.

**Comment by jakevdp** [comment]
Point being it's very abnormal to have something like ``0.4.dev0`` on PyPI.

**Comment by jakevdp** [comment]
For this I probably would have done an 0.3.1 release or something like that, because not much is changing aside from a minor version of the vega-lite libraries.

**Comment by jakevdp** [comment]
More details on Python package version conventions here: [PEP440](https://www.python.org/dev/peps/pep-0440/)

**Comment by domoritz** [comment]
Okay, I made a new 0.4.1 release. I don't know how to handle the `devx` version numbers yet. It would make sense if we had a separate release branch but if we release from master, it seems tricky to know the next release number in advance. Also, do we keep the versions in package.js and __index__.py consistent?

**Comment by jakevdp** [comment]
Yeah, my usual habit is to release, say 0.3, then change master to 0.4.dev0, then changing to 0.3.1 or 0.4 for the next release. I mainly use the ``devx`` as a marker that the version is unreleased; otherwise someone working from an old master might think they have the 0.4 release installed.

**Comment by jakevdp** [comment]
We're all set for now, I think! I'm going to update on conda-forge.
