### ISSUE TITLE
stacked area chart not rendering correctly via VegaLite.display()

### ISSUE THREAD

**Issue by SamPenrose** [vega/ipyvega#52]
The test case below works fine on http://vega.github.io/vega-editor/?mode=vega-lite but not in a notebook on a freshly built checkout of origin/master. Specifically, the larger of the two areas draws without normalization.

```
--------------- test case ----------
from vega import VegaLite
data = [
    {'count': 1532, 'date': '2016-07-05', 'label': 'group2'},
    {'count': 4712, 'date': '2016-07-05', 'label': 'group1'},
    {'count': 1736, 'date': '2016-07-06', 'label': 'group2'},
    {'count': 4970, 'date': '2016-07-06', 'label': 'group1'},
    {'count': 1960, 'date': '2016-07-07', 'label': 'group2'},
    {'count': 5248, 'date': '2016-07-07', 'label': 'group1'},
    {'count': 2002, 'date': '2016-07-08', 'label': 'group2'},
    {'count': 5360, 'date': '2016-07-08', 'label': 'group1'},
    {'count': 1969, 'date': '2016-07-09', 'label': 'group2'},
    {'count': 4548, 'date': '2016-07-09', 'label': 'group1'},
    {'count': 1931, 'date': '2016-07-10', 'label': 'group2'},
    {'count': 4631, 'date': '2016-07-10', 'label': 'group1'},
    {'count': 2316, 'date': '2016-07-11', 'label': 'group2'},
    {'count': 5817, 'date': '2016-07-11', 'label': 'group1'}]
graphic = {
    "mark": "area",
    "encoding": {
        "y": {"aggregate": "sum", "field": "count", "type": "quantitative"},
        "x": {"field": "date", "type": "temporal"},
    "color": {"field":"label", "type":"nominal", "scale": {"range": ["#e6aa06", "#1f77b4"]}}
    },
    "config": {"mark": {"stacked": "normalize"}}
}
VegaLite(graphic, data).display()
-----------------
```

**Comment by jakevdp** [comment]
I'm not sure why this is, but if you add the ``timeUnit='yearmonthdate'`` to the ``x`` encoding, you get the correct output:
```python
graphic = {
    "mark": "area",
    "encoding": {
        "y": {"aggregate": "sum", "field": "count", "type": "quantitative"},
        "x": {"field": "date", "type": "temporal", "timeUnit": "yearmonthdate"},
    "color": {"field":"label", "type":"nominal", "scale": {"range": ["#e6aa06", "#1f77b4"]}}
    },
    "config": {"mark": {"stacked": "normalize"}}
}
VegaLite(graphic, data).display()
```
![vega 9](https://cloud.githubusercontent.com/assets/781659/17531869/a639967a-5e32-11e6-88af-c85749a9a78c.png)

**Comment by SamPenrose** [comment]
Thanks so much for the quick fix! I noticed other weirdness with timeUnit interacting with stacking and bar graphs. If I can recreate it I will file an issue.

**Comment by jakevdp** [comment]
By the way, if you're building Vega-Lite visualizations in Python, have you tried [Altair](https://github.com/ellisonbg/altair) yet? It provides a nice Python API that for the most part mirrors the JSON structure. It's still under development, and we'd love any feedback.  For reference, this is how you do the above plot in altair:

```python
import pandas as pd
from altair import *

data = pd.DataFrame(data)  # DataFrame required

Chart(data).mark_area(
    stacked='normalize'
).encode(
    X('date:T', timeUnit='yearmonthdate'),
    Y('sum(count)'),
    Color('label', scale=Scale(range=["#e6aa06", "#1f77b4"]))
)
```

**Comment by SamPenrose** [comment]
Thanks for the tip about Altair. Ironically, I'm using this library to get away from having to use Pandas to draw a graphic. We are Spark plus notebooks, and I am much happier quickly rolling JSON than dropping into Pandas just to call plot(). That said, all praise to those who provide libraries for the rest of us.

**Comment by jakevdp** [comment]
In that case, you don't actually need Pandas. Think of Altair as a way to build validated Vega-Lite JSON specifications without having to hand-code JSON. For example, you can get the above JSON output like this:
```python
from altair import *

chart = Chart().mark_area(
    stacked='normalize'
).encode(
    X('date:T', timeUnit='yearmonthdate'),
    Y('sum(count)'),
    Color('label', scale=Scale(range=["#e6aa06", "#1f77b4"]))
)

chart.to_dict()
```
{'config': {'mark': {'stacked': 'normalize'}},
 'encoding': {'color': {'field': 'label',
   'scale': {'range': ['#e6aa06', '#1f77b4']}},
  'x': {'field': 'date', 'timeUnit': 'yearmonthdate', 'type': 'temporal'},
  'y': {'aggregate': 'sum', 'field': 'count'}},
 'mark': 'area'}
```

**Comment by domoritz** [comment]
Seems fixed and not related to this package.
