### ISSUE TITLE
Add warning when jupyter nbextension not installed

### ISSUE THREAD

**Issue by jakevdp** [vega/ipyvega#56]
An Altair user requested this: https://github.com/ellisonbg/altair/issues/200. The current behavior (silent failure) is not optimal for folks who skip reading the installation instructions 😄 

I'm not certain how to do this, but @ellisonbg may have a better idea.

**Comment by jakevdp** [comment]
After invesigating the ``jupyter-nbextension`` code a bit, I came up with this function:

```python
import os
from jupyter_core.paths import jupyter_path


def check_if_nbextension_installed(extname):
    paths = jupyter_path()

    for path in paths:
        if not os.path.exists(path):
            continue
        if 'nbextensions' not in os.listdir(path):
            continue
        if extname in os.listdir(os.path.join(path, 'nbextensions')):
            return True
    else:
        return False

check_if_nbextension_installed('jupyter-vega')
# True
```

Seems to work on my system, at least. We could use this sort of check in the [``_ipython_display_``](https://github.com/vega/ipyvega/blob/master/vega/base.py#L42) method and print a useful warning if the extension is not installed.

Maybe @carreau could comment on whether this snippet is the correct way of checking for the presence of an nbextension

**Comment by Carreau** [comment]
Hum.. haven't look at how extension are working in  a while. 

I'll open an issue to either document or provide a api "is installed".

I doubt we can make a definitive promise of having a perfect way to know if an extension is installed as Server and Kernel can be on different machines with non-shared file system.

**Comment by domoritz** [comment]
Luckily, we don't need to install the extension if newer versions of the notebook anymore. I think this issue is sufficiently addressed.
