### ISSUE TITLE
Refactor to use Jupyter's custom MIME type based rendering

### ISSUE THREAD

**Issue by ellisonbg** [vega/ipyvega#60]
In JupyterLab we are moving to rendering custom outputs using custom MIME types and functions that get registered to rendering those MIME types. I have that working well for JupyterLab, and am working on a version for the classic notebook. This will dramatically simplify the code base and lead to only the actual vega/vegalite JSON spec being stored in the notebook (rather than a bunch of JS code). Will also enable us to get these things working on nbviewer.

This will result in a complete refactor of basically everyfile in this repo...can I hold the lock for a few days?

@domoritz @jakevdp

**Comment by domoritz** [comment]
Sounds great. You can lock the repo.

**Comment by jakevdp** [comment]
Sure, sounds good!

**Comment by rgbkrk** [comment]
Heya! Looking forward to this.

I've done some support for the same mimetypes in https://github.com/nteract/nteract/pull/1113, it's looking great!

**Comment by domoritz** [comment]
Not needed anymore since Jupyter will come with support for Vega and Vega-Lite.
