### ISSUE TITLE
Enable copying PNG more easily

### ISSUE THREAD

**Issue by aschokking** [vega/ipyvega#63]
I end up sharing a lot of rendered graphs on Slack which has the handy ability to upload images from the clipboard. With matplotlib visualizations there's a vanilla <img> rendered that I can right-click and say 'copy image' and then just paste it into slack which works great. However with vega I have to add the intermediate step of saving the graph as a png first which really slows things down. 

I was wondering if it might be possible to add another option beside "Export as PNG" like "Copy as PNG" that would do the same operation but plop the results in the clipboard?

**Comment by domoritz** [comment]
You can just right click -> copy image.
