### ISSUE TITLE
"nbconvert"ed interactive Vega plots

### ISSUE THREAD

**Issue by jacobkolind** [vega/ipyvega#64]
Using the `nbconvert` tool, it would be nice be able to export notebooks containing Vega plots in html (and rst) format. For static plots it just works, but for good reasons all the interactive features of a plot disappear. Links to the `d3` and `vega` javascript libraries need to be added to the HTML template that is passed to `nbconvert`, and some magic to preserve the plot specification also need to happen in the preprocessing and conversion steps. 

Are you able to offer advice on how to write such magic? By calling the private functions `_generate_html` and `_generate_js` on the `vega.vega.Vega` object I can get the relevant snippets of code, but my knowledge about Jupyter and nbconvert is not deep enough to understand how I can make them survive through to the output HTML.

**Comment by jakevdp** [comment]
I'm not certain, but FYI this repo will soon be deprecated. Jupyter integration of vega will be moving to https://github.com/altair-viz/jupyterlab_vega, so any solution to this should be done there.
