### ISSUE TITLE
Update for Vega ^3.0.1

### ISSUE THREAD

**Issue by pheanex** [vega/ipyvega#67]
0.5.0 may not work correctly with Vega 3.0.1 (My guess)
If i try to run the following example from https://vega.github.io/vega/examples/force-directed-layout/
within a jupyter notebook (with the json path modified), i get an empty rendered window.
[jpynb.zip](https://github.com/vega/ipyvega/files/1257081/jpynb.zip)

**Comment by jakevdp** [comment]
Thanks! We're actually getting close to deprecating this repository in favor of a more long-term solution, so this will be worked out shortly.

**Comment by frederik-elwert** [comment]
@jakevdp Is there any information about the new solution yet? Is there a bug report or something that I can subscribe to?

**Comment by domoritz** [comment]
I think he's talking about https://github.com/altair-viz/jupyter_vega.

**Comment by falconair** [comment]
@jakevdp Any idea when the switch might happen? 

I would like to do some jupyter+vega (not vega-lite) demos for my colleagues. There are some bugs, like missing 'stratify' transform[1] and would like to know which repository I should use to debug code, or if I should wait for an update which will resolve all my issues (and get jupyter working with vega 3/vega-lite 2).

[1] https://github.com/vega/ipyvega/issues/68

**Comment by jakevdp** [comment]
I'll have time to start work on this again around the second week of October. From there it will just depend on how many more fundamental differences crop up in vegalite 1 and 2.

Regarding the switch in display method: I know about as much as you do. @ellisonbg
may have a better idea on that.

**Comment by domoritz** [comment]
I created `vega3` at https://github.com/vega/ipyvega/tree/vega3.
