### ISSUE TITLE
vega & vegalite magic functions

### ISSUE THREAD

**Issue by jakevdp** [vega/ipyvega#71]
It might be useful to add cell magics to render vega & vega-lite visualizations, e.g. something like this: https://gist.github.com/jakevdp/be41712c343934125fcdfbb1156ce2c8

This might be a good raison d'etre for this package once most of the rendering architecture is pushed into Jupyter itself via mimetype stuff.

**Comment by mhlr** [comment]
:+1:

**Comment by mhlr** [comment]
It would be extra nice if the magics accepted YAML as well as JSON.
JSON is horrible to write by hand.

**Comment by domoritz** [comment]
Is there a way to register the cell magic when the package is installed (or loaded)? Or is that an anti-pattern?

**Comment by jakevdp** [comment]
These are now part of altair
