### ISSUE TITLE
Expose vega-embed opts

### ISSUE THREAD

**Issue by meetamit** [vega/ipyvega#77]
Hi All,

I appreciate your work on making this module available. My coworkers and I would love to use this in our notebooks, but unfortunately our employer is extremely concerned about confidentiality. As such, the "Open in Vega Editor" button below the embedded player is considered a data leak risk, since it sends the data out to the www.

Would you be open to exposing a way to disable these actions? From [the source code](https://github.com/vega/ipyvega/blob/526a2eecd61ce08fd749b04615ed115602e46449/src/index.js#L44) it appears that currently there's no way to do it.

I'd be happy to contribute a PR for this. Thanks for your consideration!

**Comment by domoritz** [comment]
Hi @meetamit. Yes, it would be awesome to expose more of the options. We need to be careful with the design so that we can implement something similar in https://github.com/jupyterlab/jupyterlab/tree/master/packages/vega3-extension. We would love your PR!

**Comment by meetamit** [comment]
Thanks @domoritz. I have a working implementation of this but wanted to ask here before I document and make a PR:

1. Seems logical to make `opts` be the 3rd parameter passed to `VegaLite()` and `Vega()`, right? (example below)
2. Would it be acceptable to make `"actions": False` be the default (i.e. by default, *don't* display the action links)? 

Example:

    VegaLite(
      {
        "mark": "point",
        "encoding": {
          "y": {"type": "quantitative","field": "Acceleration"},
          "x": {"type": "quantitative","field": "Horsepower"}
        }
      },
      df, 
      {
        'renderer': 'svg', 
        'actions': { 'export':True, 'editor': False } 
      }
    )

**Comment by domoritz** [comment]
Fantastic. No, actions should remain on by default.

**Comment by domoritz** [comment]
I fear that we might need to hold off until we have decided how to move forward in https://github.com/altair-viz/altair/issues/240. The discussion is quite relevant to this issue.

**Comment by meetamit** [comment]
K, no probs. Thanks
