### ISSUE TITLE
render svg file

### ISSUE THREAD

**Issue by pagpires** [vega/ipyvega#79]
Hi, thank you guys for making ipyvega so convenient. I'm just wondering if there's a way to change the renderer. I guess the default is PNG (canvas?) but I would love to change that into SVG, which I can import into Adobe Illustrator or something like that. Does such function exists or can you guys tell me what might be the best practices?

**Comment by domoritz** [comment]
Thank you for filing the issue. I think this is high priority and should come when we support https://github.com/vega/ipyvega/issues/77.
