### ISSUE TITLE
vega3: Error on charts without data at top level

### ISSUE THREAD

**Issue by jakevdp** [vega/ipyvega#81]
Meant to open a PR but accidentally edited on the vega3 branch (sorry): https://github.com/vega/ipyvega/blob/vega3/vega3/utils.py#L90-L93

In the current release, a ValueError is raised for valid specs if they don't have data defined at the top level. (see https://github.com/altair-viz/altair/issues/747). We should get this into a release ASAP

**Comment by jakevdp** [comment]
(we should get #82 into the release too)

**Comment by jakevdp** [comment]
I could try doing a 6.1 release (I haven't done the npm build steps before), or would you like to do it?

**Comment by domoritz** [comment]
Done. 

Sure, next time you can just follow the instructions in https://github.com/vega/ipyvega#how-to-make-a-release.

**Comment by jakevdp** [comment]
Thanks!

**Comment by domoritz** [comment]
Fixed and released.
