### ISSUE TITLE
Rendering without side-effects?

### ISSUE THREAD

**Issue by jakevdp** [vega/ipyvega#83]
Comment from @Carreau at https://github.com/altair-viz/altair/issues/634

> ``_repr_*_`` should as most as possible not have side effect, that would completely break things like nbconvert.
> 
> If you want an assignment to also display you can tweak the config option of IPython.
> Yo may also try to have a repr widgets maybe instead of having side-effects ?

Can we update ipyvega and/or the altair renderer framework so that ipyvega returns a displayable object rather than calling ``display()`` as a side-effect?

**Comment by domoritz** [comment]
I don't know enough about jupyter's display methods to implement this. Do you have any pointers?

**Comment by domoritz** [comment]
Okay, I will focus on other issues then.

**Comment by jakevdp** [comment]
Looked into this a bit... basically the issue is this: currently we use ``IPython.display`` to send two mimebundles to the frontend, then return an empty mimebundle. What would be better would be just to return a single HTML or Javascript mimebundle instead... I tried the easy thing of returning a single HTML mimebundle with embedded javascript, but I don't know how to grab access to the output area this way (the javascript ``this`` statement returns the output area when displaying javascript, and returns null when that javascript is embedded in an HTML display).

Figuring that out would be the best way forward.

**Comment by chmp** [comment]
Not sure, whether I understand the problem correctly. However, what I usually do is to use the a single javascript output and create the required elements via the DOM API. The javascript code has access to a div inside the output area, wrapped by jQuery and exposed as `element`. As a test, I used a simplified version of the `vega.js` code (I replaced `render` with a direct call to `vegaEmbed`). For me the following works (in jupyter notebook):

```python
source = """
require(['nbextensions/jupyter-vega/index'], function(vega) {{
  var spec = {spec};
  
  var target = document.createElement('div');
  target.className = 'vega-embed';
  
  var style = document.createElement('style');
  style.textContent = [
    '.vega-embed .error p {{',
    '  color: firebrick;',
    '  font-size: 14px;',
    '}}',
  ].join('\\n');
  
  var el = element[0];
  el.appendChild(target);
  el.appendChild(style);
  
  vega.vegaEmbed(target, spec);
}}, function (err) {{
  if (err.requireType !== 'scripterror') {{
    throw(err);
  }}
}});
"""

class ChartWrapper:
    def __init__(self, chart):
        self.chart = chart
        
    def _repr_mimebundle_(self, include=None, exclude=None):
        return {
            'application/javascript': source.format(spec=self.chart.to_json())
        }

ChartWrapper(chart)
```

If you do not need the custom styling of the errors, the simpler option would be to embed the vega chart directly into the element, i.e., 

```javascript
var spec = {spec};
vega.vegaEmbed(element[0], spec);
```

**Comment by domoritz** [comment]
@chmp Thank you so much for the PRs! I left a few comments but overall I really like the approach.

**Comment by domoritz** [comment]
Done in https://github.com/vega/ipyvega/pull/95
