### ISSUE TITLE
Style embed

### ISSUE THREAD

**Issue by domoritz** [vega/ipyvega#84]
The actions could be hidden by default. I think it makes sense to create a style in embed that can be used everywhere.

**Comment by domoritz** [comment]
I'm imagining that wherever we use embed, we use a common style like https://github.com/vega/vega-embed/blob/master/vega-embed.css.

**Comment by jakevdp** [comment]
Ah, that makes sense.

**Comment by domoritz** [comment]
What are your thoughts on hiding the embed actions and showing them on hover?

**Comment by jakevdp** [comment]
I think that could be good
