### ISSUE TITLE
feature request - display chart from filename/url 

### ISSUE THREAD

**Issue by iliatimofeev** [vega/ipyvega#86]
Is it possible to show char from url like  `IPython.display.Image('my_image.png')` do?
```python
from vega import VegaLite
VegaLite(url='bar_chart_with_labels.vl.json')
```

**Comment by domoritz** [comment]
You can load the json from file and pass the parsed dict.

With #33, you would be able to pass the file content directly but we don't support that yet.

**Comment by domoritz** [comment]
In the spirit of separation of concerns, I would say that loading a parsing JSON is simple enough in Python and should be handled outside of this library.
